### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by scankannan** [vertilux/sage300-cli#1]
Hi would you be able to post some of the screenshots of the application? thanks for sharing the code and the approach to set it up.

**Comment by lepepe** [comment]
Hi @scankannan this repo is not close to a finish project. By now is just a simple CLI app to calculate sales, get financial statements previews and open orders.
![2020-10-19_11-51](https://user-images.githubusercontent.com/12739553/96473976-47de8f00-1200-11eb-9f71-242b1f78d840.png)

**Comment by scankannan** [comment]
Thank you Pepe 👍
